version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./zookeeper:/bitnami/zookeeper
    restart: always

  kafka:
    image: bitnami/kafka:3.2.3
    ports:
      - '9092:9092'
      - '9999:9999'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${DOCKER_HOST_IP:-127.0.0.1}:9092            # 给客户端访问的地址
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes                     # 允许使用PLAINTEXT协议(镜像中默认为关闭,需要手动开启)
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false        # 关闭自动创建 topic 功能
      - KAFKA_CFG_LOG_RETENTION_HOURS=6                  # 全局消息过期时间 6 小时(测试时可以设置短一点)
      - JMX_PORT=9999                                   # 开启JMX监控
    volumes:
      - ./kafka:/bitnami/kafka
    depends_on:
      - zookeeper
    restart: always

  # Web 管理界面 另外也可以用exporter+prometheus+grafana的方式来监控 https://github.com/danielqsj/kafka_exporter
  kafka_manager:
    image: 'hlebalbau/kafka-manager:3.0.0.5-7e7a22e'
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: SecretKey2333
    depends_on:
      - zookeeper
      - kafka
    restart: always